config/routes.rb
RottenMangoes::Application.routes.draw do
  # namespace :admin do
  #   get 'users/show'
  # end

  # namespace :admin do
  #   get 'users/edit'
  # end

  # namespace :admin do
  #   get 'users/index'
  # end

  # get 'users/show'

  # get 'actors/show'

  # get 'actors/new'

  # get 'actors/create'

  # get 'actors/edit'

  # Nested resources: a review belongs to movie
  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :actors

  root to: 'movies#index'

  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update, :destroy]
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MoviesHelper

  def index
    if params[:title_or_director]
      # v1
      # @movies = Movie.where(
      #   "title LIKE ? AND director LIKE ? AND runtime_in_minutes BETWEEN ? AND ?",
      #   query_title(params[:title]), 
      #   query_director(params[:director]), 
      #   query_range_runtime(params[:runtime_in_minutes])[0],
      #   query_range_runtime(params[:runtime_in_minutes])[1]
      # )
      # v2
      # @movies = Movie.movies_filter(
      #   query_title(params[:title]), 
      #   query_director(params[:director]), 
      #   query_range_runtime(params[:runtime_in_minutes])[0],
      #   query_range_runtime(params[:runtime_in_minutes])[1]
      # )
      # v3
      # @movies = Movie.title_filter(query_title(params[:title])).
      #                 director_filter(query_director(params[:director])).
      #                 runtime_filter(query_range_runtime(params[:runtime_in_minutes])[0],query_range_runtime(params[:runtime_in_minutes])[1])
      # v4
      @movies = Movie.title_or_director_filter(params[:title_or_director].strip).
                      runtime_filter(query_range_runtime(params[:runtime_in_minutes])[0],query_range_runtime(params[:runtime_in_minutes])[1])
    end
    @movies ||= Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      # Flash notice/alert: app/views/layouts/application.html.erb
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end

  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end

  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected
  # Strong params
  # Whitelist attributes within the context in which they will be used, rather than requiring a global whitelisting within the model.
  def movie_params
    # Required parameter movie
    # Permit indentifies the list of allowed parameter keys

    params.require(:movie).permit(:title, :release_date, :director, :runtime_in_minutes, :description, :poster_image_url, :image)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
  def query_title(title)
    "%#{title}%"
  end
    
  def query_director(director)
    "%#{director}%"
  end

  def query_range_runtime(statement)
    case statement
    when "Any"
      [0, 1000]
    when "Under 90 minutes"
      [0, 89]
    when "Between 90 and 120 minutes"
      [90, 120]
    when "Between 120 and 150 minutes"
      [121, 150]
    when "Over 150 minutes"
      [151, 500]
    end
  end

end

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:

      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>


  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>

  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
<!--
  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </div> -->
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :poster_image_url, "or image URL" %><br />
    <%= f.text_field :poster_image_url %>
  </p>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/movies/_movie.html.erb

<% if movie.poster_image_url != nil and movie.poster_image_url != '' %>
    <%= link_to image_tag(movie.poster_image_url, :height => '50%', :width => '50%'), movie_path(movie) %>
  <% else %>
    <%= link_to image_tag(movie.image, :height => '50%', :width => '50%'), movie_path(movie) %>
  <% end %><h2><%= link_to movie.title, movie_path(movie) %></h2>
<h2>
  <%= movie.review_average %>/10
</h2>

<h3>
  <%= formatted_date(movie.release_date) %>
</h3>

<h4>
  Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes
</h4>

<p>
  <%= movie.description %>
</p>

<hr>


app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

<!-- 
<%= form_for @movie do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>

  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>

  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Submit" %> 
  </div>

<% end %> 
-->

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>

<%= link_to "Submit a movie!", new_movie_path %>
<!-- 
<%= link_to "Login", new_session_path %>

<%= link_to "Sign up", new_user_path %>
 -->
<hr>

<%= form_tag movies_path, method: "GET" do %>
  <h4>Search by:</h4>
  <%= label_tag(:title_or_director, "Title/Director:") %> 
  <%= text_field_tag :title_or_director, nil, placeholder: "Search by title or director" %>
  <!-- 
	<%= label_tag(:title, "Title:") %> 
  <%= text_field_tag :title, nil, placeholder: "Search by title" %>
  <%= label_tag(:director, "Director:") %>
  <%= text_field_tag :director, nil, placeholder: "Search by director" %>
 	-->
  <%= label_tag(:runtime_in_minutes, "Runtime") %>
  <%= select_tag(:runtime_in_minutes, options_for_select(["Any", "Under 90 minutes", "Between 90 and 120 minutes", "Between 120 and 150 minutes", "Over 150 minutes"])) %>

  <%= submit_tag("Search") %>

<% end %>

<br>
<hr>

<%= render @movies %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>

<%= image_tag @movie.poster_image_url(:thumb) if @movie.poster_image_url? %>

<%= render 'form' %>

<!-- 
<%= form_for @movie do |f| %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>

  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>

  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit "Submit" %> 
  </div>

<% end %> 
-->

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<% if @movie.poster_image_url != nil and @movie.poster_image_url != '' %>
  <%= link_to image_tag(@movie.poster_image_url, :height => '50%', :width => '50%'), movie_path(@movie) %>
<% else %>
  <%= link_to image_tag(@movie.image, :height => '50%', :width => '50%'), movie_path(@movie) %>
<% end %>


<h2>
	<%= @movie.title %> (<%= @movie.review_average %>/10) (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)
</h2>

<% @movie.actors.each do |actor| %>
  <%= link_to actor.full_name, actor_path(actor)  %>
  <%= raw '<br>' unless actor == @movie.actors.last %>
<% end %>

<!-- Formated date from helper movies_helper.rb -->
<h3>
	<%= formatted_date(@movie.release_date) %>
</h3>

<h4>
	Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes
</h4>

<p>
	<%= @movie.description %>
</p>




<h3>Reviews of <em><%= @movie.title %></em></h3>
<!-- If logged -->
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= link_to review.user.full_name, user_path(review.user) %> (<%= review.user.email %>) </small><br/>
  
  <% end %>
  
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>

<!-- Not logged -->
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 

<% end %>