config/routes.rb
RottenMangoes::Application.routes.draw do
  # namespace :admin do
  #   get 'users/show'
  # end

  # namespace :admin do
  #   get 'users/edit'
  # end

  # namespace :admin do
  #   get 'users/index'
  # end

  # get 'users/show'

  # get 'actors/show'

  # get 'actors/new'

  # get 'actors/create'

  # get 'actors/edit'

  # Nested resources: a review belongs to movie
  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :actors

  root to: 'movies#index'

  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # access all reviews that belong to a user
  has_many :reviews, dependent: :destroy

  has_secure_password

  def review_average
    self.reviews.sum(:rating_out_of_ten)/(self.reviews.size == 0 ? 1 : self.reviews.size)
  end

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :auth_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # Flash notice/alert: app/views/layouts/application.html.erb
      redirect_to admin_users_path, notice: "#{@user.full_name} was updated successfully!"
    else
      render :index
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.delete_mail(@user).deliver_later
    @user.destroy
    redirect_to admin_users_path
  end

  def auth_admin
    if !user_is_admin?
      flash[:error] = "You must log in as Admin to access this page, Mr. Not Admin Guy!"
      redirect_to new_session_path
    end
  end

  protected
  # Strong params
  # Whitelist attributes within the context in which they will be used, rather than requiring a global whitelisting within the model.
  def user_params
    # Required parameter user
    # Permit indentifies the list of allowed parameter keys

    params.require(:user).permit(:email,:firstname, :lastname, :password, :password_confirmation, :admin)
  end


  private



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)

    if current_user != nil && current_user.admin
      if @user.save
        redirect_to admin_users_path, notice: "User #{@user.firstname} created!"
      else
        redirect_to admin_users_path, notice: "User creation failed"
      end
    else
      respond_to do |format|
        if @user.save
          # Tell the UserMailer to send a welcome email after save
          session[:user_id] = @user.id # auto log in
          UserMailer.welcome_mail(@user).deliver_later

          format.html { redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!" }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      
      end

    end

  end

  protected

  def user_params
    params.require(:user).permit(:email,:firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admin/users/_form.html.erb
<%= form_for @user, :url => admin_users_path do |f| %>

  <% if @user.errors.any? %>
    
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>

  <% end %>
  
  
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  

  <% if current_user && current_user.admin %>
    <div>
      <%= f.label "Set as Admin" %> <br>
      <%= f.check_box :admin %>
    </div>
  <% end %>
  
  <div><%= f.submit "Submit" %></div> 

<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit user <%= @user.full_name %></h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<%= link_to "Back to main page  ", movies_path %> | 
<%= link_to "Create a User", new_user_path %>
<br/>



<% @users.each do |user| %>
  <p><%= link_to user.full_name, admin_user_path(user) %> <%= user.email %> 
    <% if user.admin %>
      (admin)
    <% end %>
  </p>
<% end %>

app/views/admin/users/show.html.erb
<%= link_to "Back to admin page  ", admin_users_path %><br/>

<h1><%= @user.full_name %> <% if @user != current_user %> (<%= link_to "delete", admin_user_path(@user), method: :delete, data: {confirm: "You sure?"}%>) <% end %></h1>
<h3><%= @user.email %></h3>
<p><b>Created at </b><p> <em><%= @user.created_at %></em>
<!-- <p><b>Last update </b><p> <em><%= @user.updated_at %></em> -->