config/routes.rb
RottenMangoes::Application.routes.draw do
  # namespace :admin do
  #   get 'users/show'
  # end

  # namespace :admin do
  #   get 'users/edit'
  # end

  # namespace :admin do
  #   get 'users/index'
  # end

  # get 'users/show'

  # get 'actors/show'

  # get 'actors/new'

  # get 'actors/create'

  # get 'actors/edit'

  # Nested resources: a review belongs to movie
  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :actors

  root to: 'movies#index'

  namespace :admin do
    resources :users, only: [:index, :edit, :show, :update, :destroy]
  end

end

app/views/layouts/_footer.html.erb
<footer>

<small>
	<% if current_user %>
      <% if current_user.admin %>
        Signed in as <%= link_to current_user.full_name, user_path(current_user) %> (<%= current_user.email %>) (<%= link_to "AdminPage", admin_users_path %> |

      <% else %>
        Signed in as <%= link_to current_user.full_name, user_path(current_user) %> (<%= current_user.email %>) (
      <% end %>
			<%= link_to "Log out", session_path(session[:user_id]), method: :delete %>)
	<% else %>
    <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
	<% end %>
</small>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RottenMangoes</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<!-- flash notices/alerts -->
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>

  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</body>

</html>